version: "3.8"
services:
  backend:
    image: backend-book
    build:
      context: ./book-backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - ./book-backend/.env

  frontend:
    image: frontend-book
    build:
      context: ./book-frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
